### PR TITLE
Add support for transcoding to/from any supported format

### PR DESCRIPTION
**Pull request by prollin**
ManagedPVRTC (used in MonoGame) only support compressing to PVRTC. PVRTexLib actually support transcoding/compressing to and from a large number of formats including DXT and ETC1 (the later is guarantied to be supported by all Android devices).

PVRTexLib can be used for all texture processing needs in order to ensure consistent result across all platforms.

This extra API is a first step to improve texture compression (and general processing) support for MonoGame. It is implemented as a separate `Transcode` function (might be better to call it `Process` since it could be used to perform resize or mipmap only operations as well). 

Hopefully this PR can start a discussion :) I am willing to spend some time on this so all feedback welcome.

### CODE REVIEW

**Comment by tomspilman** [comment]
This seems reasonable to me.

@KonajuGames - Thoughts?

**Comment by KonajuGames** [comment]
I had no idea PVRTexLib supported those extra formats.  It is called _PVR_ TexLib after all. :)

I was looking at building rg_etc1 for the different platforms or porting rg_etc1 to C#, but if PVRTexLib already supports it and more (I see it also supports ETC2 which will be handy for future use), I'm all for it.

**Comment by prollin** [comment]
@KonajuGames _PVR_ is actually a container file format (same way DDS is), not to be mistaken with PVRTC which is the compression format.
rg_etc1 seem to be the fastest out there, but then it adds another dependency.

We spent a lot of time looking at options, and we have been using PVRTexLib for a while without issues with a custom TextureProcessor and some black magic to make it work with the old content pipeline. We are now trying to switch to the new Pipeline tool.

I did a quick test with the Pipeline.exe tool by replacing the dll in MonoGame.Dependencies and things look good so far. It will have to be tested on Linux and MacOSX though.

**Comment by mgarstenauer** [comment]
Perhaps I overlooked something, but: CompressTexture() and your new Transcode() methods allocate memory using new[] and pass this memory on to the caller. I don't see a way to free this memory from .NET? Is this a memory leak?

**Comment by KonajuGames** [comment]
> Is this a memory leak?

It's an unmanaged resource that would need to be explicitly released.

**Comment by tomspilman** [comment]
>  I don't see a way to free this memory from .NET? 

Generally you use `Marshal.FreeHGlobal` to free it.

**Comment by mgarstenauer** [comment]
> > I don't see a way to free this memory from .NET?
> 
> Generally you use Marshal.FreeHGlobal to free it.

Sorry if I was unclear. What I wanted to point out is: CompressTexture() allocates two memory blocks (dataSize and returnData) using C++ new[]. I am not aware of a way to free this memory in .NET. `Marshal.FreeHGlobal` can only free memory allocated with Win32 `LocalAlloc`.

I don't see the memory being freed in MonoGame: [GraphicsUtil.CompressPvrtc](https://github.com/mono/MonoGame/blob/7c9790b8901b6a8f59a668a2954649b67d74500b/MonoGame.Framework.Content.Pipeline/Graphics/GraphicsUtil.cs)

I suspect a memory leak. There should be a separate method in the DLL that frees the memory with C++ delete[].

Reference:
http://stackoverflow.com/questions/12273961/release-unmanaged-memory-from-managed-c-sharp-with-pointer-of-it

**Comment by KonajuGames** [comment]
That is correct. This is a memory leak and does need another native
function to free the memory.

**Comment by prollin** [comment]
It is indeed a leak. I quickly copied the behavior of the Compress method to make this PR as simple as possible for a first review.

We can create a set of API that better mimic what is available in PVRTexLib.
Something like this:
CreateTexture()
GenerateMipmaps()
Resize()
Transcode()
GetTextureDataSize()
GetTextureData()
DestroyTexture()

CreateTexture() creates a PVRTexture object. We only need one at a time so no need to bother with handles; Calling CreateTexture() multiple times simply destroy the previous one and create a new one.

GetTextureData() would need to be provided with an already allocated byte buffer (this would avoid any potential issues with returning a pointer to unmanaged memory); GetTextureDataSize() can be used to retrieve the size to allocate.

DestroyTexture would make sure all unmanaged resources are properly released.

This is just a quick idea. I can make those changes and submit a new PR fairly quickly if you guys are ok with those changes.

**Comment by prollin** [comment]
Did a quick implementation of the improvements discussed above for your review. It should solve the leak issue as well.

I did some renaming for clarity since I figured this lib could be useful for other .NET developers

**Comment by tomspilman** [comment]
I guess you are proposing we rename the project from "ManagedPVRTC" to "PVRTexLib.NET"?

**Comment by prollin** [comment]
@tomspilman that is just a suggestion. It aligns nicely with "PVRTexLibWrapper", "ManagedPVRTC" was confusing since the lib doesn't only deal with PVRTC.

I can very well revert those name changes to keep them at a minimum. Creating a completely different repo could also be an option.

**Comment by prollin** [comment]
Closing this PR; published a new wrapper [here](https://github.com/flyingdevelopmentstudio/PVRTexLibNET)

**Pull request closed without merging**
